# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data\UI\mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox.setFlat(True)
        self.horizontalGroupBox.setCheckable(False)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_url = QtWidgets.QLineEdit(self.horizontalGroupBox)
        self.input_url.setObjectName("input_url")
        self.horizontalLayout_4.addWidget(self.input_url)
        self.search_button = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_4.addWidget(self.search_button)
        self.horizontalLayout_4.setStretch(0, 6)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox)
        self.result_list_box = QtWidgets.QGroupBox(self.centralwidget)
        self.result_list_box.setFlat(True)
        self.result_list_box.setObjectName("result_list_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.result_list_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.result_list = QtWidgets.QListWidget(self.result_list_box)
        self.result_list.setObjectName("result_list")
        self.verticalLayout_3.addWidget(self.result_list)
        self.verticalLayout_2.addWidget(self.result_list_box)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox_2.setFlat(True)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.save_dir_display = QtWidgets.QLineEdit(self.horizontalGroupBox_2)
        self.save_dir_display.setEnabled(True)
        self.save_dir_display.setObjectName("save_dir_display")
        self.horizontalLayout_5.addWidget(self.save_dir_display)
        self.save_dir_button = QtWidgets.QToolButton(self.horizontalGroupBox_2)
        self.save_dir_button.setObjectName("save_dir_button")
        self.horizontalLayout_5.addWidget(self.save_dir_button)
        self.horizontalLayout_5.setStretch(0, 6)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_6.addWidget(self.download_button)
        self.download_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.download_bar.setProperty("value", 24)
        self.download_bar.setObjectName("download_bar")
        self.horizontalLayout_6.addWidget(self.download_bar)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.setStretch(1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "Download URL"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.result_list_box.setTitle(_translate("MainWindow", "Found Video"))
        self.horizontalGroupBox_2.setTitle(_translate("MainWindow", "Save Folder"))
        self.save_dir_button.setText(_translate("MainWindow", "..."))
        self.download_button.setText(_translate("MainWindow", "Download"))
